Repository Calixte-Williams/set08803_gw, pull requests merged in 2024-04, with the labels that each got.

#80 Add Jermon's Countries by Region Report
  Dockerfile
  pom.xml
  src/main/java/com/napier/sem/App.java
Labels: cw1

#81 Feature/mergepopulationreports
  Dockerfile
  pom.xml
  screenshots-for-table/Report4.png
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/CapitalCity.java
  src/main/java/com/napier/sem/City.java
  src/main/java/com/napier/sem/Country.java
  src/main/java/com/napier/sem/Language.java
  src/main/java/com/napier/sem/Population.java
Labels: enhancement, cw2

#82 Updated the headings of each method excluding the methods displaying …
  src/main/java/com/napier/sem/App.java
Labels: enhancement, cw2

#84 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: documentation, enhancement, cw2

#83 Feature/unit testing
  .github/workflows/main.yml
  Dockerfile
  docker-compose.yml
  pom.xml
  set08803_gw.iml
  src/main/java/com/napier/sem/App.java
  src/test/java/com/napier/sem/AppTest.java
Labels: bug, enhancement, cw2

#85 Feature/method corrections
  SET08803 Group One - Contribution Table.xlsx
  src/main/java/com/napier/sem/App.java
  src/test/java/com/napier/sem/AppTest.java
Labels: documentation, cw2

#86 Add code coverage
  .DS_Store
  .github/workflows/main.yml
  pom.xml
  src/test/java/com/napier/sem/AppIntegrationTest.java
Labels: bug, enhancement, cw2

#88 Feature/addingtable
  README.md
  screenshots-for-table/C-sort-by-pop.png
  screenshots-for-table/Citi-in-wrld.png
  screenshots-for-table/CitiSbypop-regi.png
  screenshots-for-table/Co-World-Pop.png
  screenshots-for-table/Co-in-Cnt.png
  screenshots-for-table/Co-in-re.png
  screenshots-for-table/TopNCo-Cnt-pop.png
  screenshots-for-table/capciti-cntbypop.png
  screenshots-for-table/capciti-regbypop.png
  screenshots-for-table/capciti-wrldbypop.png
  screenshots-for-table/citiBypop-cnt.png
  screenshots-for-table/citiSbypop-Dis.png
  screenshots-for-table/citiSbypop-wrld.png
  screenshots-for-table/citibypop-Co.png
  screenshots-for-table/popofppl-cnt.png
  screenshots-for-table/popofppl-co.png
  screenshots-for-table/popofppl-reg.png
  screenshots-for-table/topCo-in-regi.png
  screenshots-for-table/topcapciti-cntbypop.png
  screenshots-for-table/topcapcitibypop.png
  screenshots-for-table/topciti-regbypop.png
  screenshots-for-table/topcitiSbypop-cnt.png
  screenshots-for-table/topcitibypop-co.png
  screenshots-for-table/topcitibypop-dis.png
  screenshots-for-table/topcitibypop-regi.png
  screenshots-for-table/totalnumofspk.png
  screenshots-for-table/totals.png
Labels: documentation, cw2

#89 Update Branch Info for code coverage badge
  README.md
Labels: cw2

#90 Update Branch Info for code coverage badge on master
  README.md
Labels: cw2

#93 Add deploy to main.yml
  pom.xml
Labels: cw2
