Repository Calixte-Williams/set08803_gw, pull requests merged in 2024-03, with the labels that each got.

#63 Feature/readme kanban
  README.md
Labels: cw1

#66 Update Code, Use-Case, Country class and Version Number
  Dockerfile
  db/world/Dockerfile
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/Country.java
  use-cases/World Countries by Population - Report.puml
Labels: documentation, enhancement, cw1

#70 Update Readme title
  README.md
Labels: documentation

#71 Feature/updating comments
  src/main/java/com/napier/sem/App.java
Labels: documentation
